<?php
$province = [
    "Bình Định" => [
        "Hoài Ân",
        "Hoài Nhơn",
        "An Lão",
        "An Nhơn",
        "Tây Sơn",
        "Tuy Phước",
        "Vân Canh",
        "Vĩnh Thạnh",
        "Phù Cát",
        "Phù Mỹ",
        "Quy Nhơn",
    ],
    "TP Hồ Chí Minh" => [
        "Hóc Môn",
        "Tân Bình",
        "Tân Phú",
        "Bình Chánh",
        "Bình Tân",
        "Bình Thạnh",
        "Thủ Đức",
        "Cần Giờ",
        "Củ Chi",
        "Nhà Bè",
        "Phú Nhuận",
        "Gò Vấp",
        "Quận 1",
        "Quận 2",
        "Quận 3",
        "Quận 4",
        "Quận 5",
        "Quận 6",
        "Quận 7",
        "Quận 8",
        "Quận 9",
        "Quận 10",
        "Quận 11",
        "Quận 12",
    ],
    "Thừa Thiên - Huế" => [
        "A Lưới",
        "Huế",
        "Hương Thủy",
        "Hương Trà",
        "Nam Đông",
        "Phong Điền",
        "Phú Lộc",
        "Phú Vang",
        "Quảng Điền",
    ],
    "An Giang" => [
        "An Phú",
        "Tân Châu",
        "Thoại Sơn",
        "Long Xuyên",
        "Châu Đốc",
        "Châu Phú",
        "Châu Thành",
        "Tịnh Biên",
        "Tri Tôn",
        "Chợ Mới",
        "Phú Tân",
    ],
    "Bà Rịa - Vũng Tàu" => [
        "Bà Rịa",
        "Long Điền",
        "Châu Đức",
        "Côn Đảo",
        "Đất Đỏ",
        "Vũng Tàu",
        "Xuyên Mộc",
        "Phú Mỹ",
    ],
    "Bắc Giang" => [
        "Sơn Động",
        "Bắc Giang",
        "Tân Yên",
        "Lạng Giang",
        "Lục Nam",
        "Lục Ngạn",
        "Việt Yên",
        "Yên Dũng",
        "Yên Thế",
        "Hiệp Hòa",
    ],
    "Bắc Kạn" => [
        "Ba Bể",
        "Bạch Thông",
        "Bắc Kạn",
        "Chợ Đồn",
        "Chợ Mới",
        "Na Rì",
        "Ngân Sơn",
        "Pác Nặm",
    ],
    "Bạc Liêu" => [
        "Hồng Dân",
        "Bạc Liêu",
        "Vĩnh Lợi",
        "Đông Hải",
        "Phước Long",
        "Giá Rai",
        "Hoà Bình",
    ],
    "Bắc Ninh" => [
        "Bắc Ninh",
        "Thuận Thành",
        "Lương Tài",
        "Tiên Du",
        "Từ Sơn",
        "Yên Phong",
        "Gia Bình",
        "Quế Võ",
    ],
    "Bến Tre" => [
        "Ba Tri",
        "Bến Tre",
        "Bình Đại",
        "Thạnh Phú",
        "Châu Thành",
        "Mỏ Cày Bắc",
        "Mỏ Cày Nam",
        "Chợ Lách",
        "Giồng Trôm",
    ],
    "Bình Dương" => [
        "Bàu Bàng",
        "Bắc Tân Uyên",
        "Tân Uyên",
        "Bến Cát",
        "Thủ Dầu Một",
        "Thuận An",
        "Dầu Tiếng",
        "Dĩ An",
        "Phú Giáo",
    ],
    "Bình Phước" => [
        "Hớn Quản",
        "Bình Long",
        "Bù Đăng",
        "Bù Đốp",
        "Bù Gia Mập",
        "Lộc Ninh",
        "Chơn Thành",
        "Đồng Phú",
        "Phú Riềng",
        "Đồng Xoài",
        "Phước Long",
    ],
    "Bình Thuận" => [
        "Tánh Linh",
        "Bắc Bình",
        "La Gi",
        "Tuy Phong",
        "Phan Thiết",
        "Phú Quý",
        "Đức Linh",
        "Hàm Tân",
        "Hàm Thuận Bắc",
        "Hàm Thuận Nam",
    ],
    "Cà Mau" => [
        "Cà Mau",
        "Cái Nước",
        "Thới Bình",
        "Trần Văn Thời",
        "U Minh",
        "Năm Căn",
        "Ngọc Hiển",
        "Đầm Dơi",
        "Phú Tân",
    ],
    "Cần Thơ" => [
        "Bình Thủy",
        "Cái Răng",
        "Thốt Nốt",
        "Thới Lai",
        "Cờ Đỏ",
        "Vĩnh Thạnh",
        "Ninh Kiều",
        "Ô Môn",
        "Phong Điền",
    ],
    "Cao Bằng" => [
        "Bảo Lạc",
        "Bảo Lâm",
        "Thạch An",
        "Cao Bằng",
        "Thông Nông",
        "Trà Lĩnh",
        "Trùng Khánh",
        "Nguyên Bình",
        "Phục Hòa",
        "Quảng Uyên",
        "Hà Quảng",
        "Hạ Lang",
        "Hòa An",
    ],
    "Đà Nẵng" => [
        "Hòa Vang",
        "Hoàng Sa",
        "Sơn Trà",
        "Thanh Khê",
        "Liên Chiểu",
        "Cẩm Lệ",
        "Ngũ Hành Sơn",
        "Hải Châu",
    ],
    "Đắk Lắk" => [
        "Krông Ana",
        "Krông Bông",
        "Krông Búk",
        "Krông Năng",
        "Krông Pắk",
        "Buôn Đôn",
        "Buôn Hồ",
        "Buôn Ma Thuột",
        "Lắk",
        "M'Đrăk",
        "Cư Kuin",
        "Cư M'gar",
        "Ea H'leo",
        "Ea Kar",
        "Ea Súp",
    ],
    "Đắk Nông" => [
        "Krông Nô",
        "Tuy Đức",
        "Cư Jút",
        "Đắk Glong",
        "Đắk Mil",
        "Đắk R'lấp",
        "Đăk Song",
        "Gia Nghĩa",
    ],
    "Điện Biên" => [
        "Mường Ảng",
        "Mường Chà",
        "Mường Lay",
        "Mường Nhé",
        "Tủa Chùa",
        "Tuần Giáo",
        "Nậm Pồ",
        "Điện Biên",
        "Điện Biên Đông",
        "Điện Biên Phủ",
    ],
    "Đồng Nai" => [
        "Tân Phú",
        "Biên Hòa",
        "Thống Nhất",
        "Long Khánh",
        "Long Thành",
        "Cẩm Mỹ",
        "Trảng Bom",
        "Vĩnh Cửu",
        "Nhơn Trạch",
        "Định Quán",
        "Xuân Lộc",
    ],
    "Đồng Tháp" => [
        "Hồng Ngự",
        "Hồng Ngự",
        "Tam Nông",
        "Tân Hồng",
        "Thanh Bình",
        "Lai Vung",
        "Lấp Vò",
        "Tháp Mười",
        "Cao Lãnh",
        "Cao Lãnh",
        "Châu Thành",
        "Sa Đéc",
    ],
    "Gia Lai" => [
        "An Khê",
        "Ayun Pa",
        "Ia Grai",
        "Ia Pa",
        "K'Bang",
        "Kông Chro",
        "Krông Pa",
        "Mang Yang",
        "Chư Păh",
        "Chư Prông",
        "Chư Pưh",
        "Chư Sê",
        "Đắk Đoa",
        "Đak Pơ",
        "Phú Thiện",
        "Đức Cơ",
        "Pleiku",
    ],
    "Hà Giang" => [
        "Hoàng Su Phì",
        "Bắc Mê",
        "Bắc Quang",
        "Mèo Vạc",
        "Vị Xuyên",
        "Xín Mần",
        "Yên Minh",
        "Đồng Văn",
        "Quản Bạ",
        "Quang Bình",
        "Hà Giang",
    ],
    "Hà Nam" => [
        "Kim Bảng",
        "Bình Lục",
        "Thanh Liêm",
        "Lý Nhân",
        "Duy Tiên",
        "Phủ Lý",
    ],
    "Hà Nội" => [
        "Hoài Đức",
        "Sóc Sơn",
        "Hoàn Kiếm",
        "Hoàng Mai",
        "Ba Đình",
        "Sơn Tây",
        "Ba Vì",
        "Bắc Từ Liêm",
        "Tây Hồ",
        "Thạch Thất",
        "Thanh Oai",
        "Thanh Trì",
        "Thanh Xuân",
        "Long Biên",
        "Thường Tín",
        "Cầu Giấy",
        "Mê Linh",
        "Mỹ Đức",
        "Chương Mỹ",
        "Nam Từ Liêm",
        "Ứng Hòa",
        "Đan Phượng",
        "Đông Anh",
        "Đống Đa",
        "Phú Xuyên",
        "Phúc Thọ",
        "Gia Lâm",
        "Hà Đông",
        "Hai Bà Trưng",
        "Quốc Oai",
    ],
    "Hà Tĩnh" => [
        "Hồng Lĩnh",
        "Hương Khê",
        "Hương Sơn",
        "Thạch Hà",
        "Kỳ Anh",
        "Kỳ Anh",
        "Can Lộc",
        "Lộc Hà",
        "Cẩm Xuyên",
        "Nghi Xuân",
        "Vũ Quang",
        "Đức Thọ",
        "Hà Tĩnh",
    ],
    "Hải Dương" => [
        "Kim Thành",
        "Kinh Môn",
        "Bình Giang",
        "Thanh Hà",
        "Thanh Miện",
        "Cẩm Giàng",
        "Chí Linh",
        "Tứ Kỳ",
        "Nam Sách",
        "Ninh Giang",
        "Gia Lộc",
        "Hải Dương",
    ],
    "Hải Phòng" => [
        "An Dương",
        "An Lão",
        "Hồng Bàng",
        "Bạch Long Vĩ",
        "Kiến An",
        "Kiến Thụy",
        "Lê Chân",
        "Cát Hải",
        "Thuỷ Nguyên",
        "Tiên Lãng",
        "Dương Kinh",
        "Ngô Quyền",
        "Vĩnh Bảo",
        "Đồ Sơn",
        "Hải An",
    ],
    "Hậu Giang" => [
        "Long Mỹ",
        "Long Mỹ",
        "Châu Thành",
        "Châu Thành A",
        "Ngã Bảy",
        "Vị Thanh",
        "Vị Thủy",
        "Phụng Hiệp",
    ],
    "Hoà Bình" => [
        "Tân Lạc",
        "Kim Bôi",
        "Kỳ Sơn",
        "Lạc Sơn",
        "Lạc Thủy",
        "Cao Phong",
        "Lương Sơn",
        "Mai Châu",
        "Đà Bắc",
        "Yên Thủy",
        "Hoà Bình",
    ],
    "Hưng Yên" => [
        "Ân Thi",
        "Hưng Yên",
        "Khoái Châu",
        "Kim Động",
        "Tiên Lữ",
        "Mỹ Hào",
        "Văn Giang",
        "Văn Lâm",
        "Yên Mỹ",
        "Phù Cừ",
    ],
    "Khánh Hòa" => [
        "Khánh Sơn",
        "Khánh Vĩnh",
        "Cam Lâm",
        "Cam Ranh",
        "Trường Sa",
        "Vạn Ninh",
        "Diên Khánh",
        "Nha Trang",
        "Ninh Hòa",
    ],
    "Kiên Giang" => [
        "An Biên",
        "An Minh",
        "Hòn Đất",
        "Tân Hiệp",
        "Kiên Hải",
        "Kiên Lương",
        "Châu Thành",
        "U Minh Thượng",
        "Vĩnh Thuận",
        "Phú Quốc",
        "Giang Thành",
        "Giồng Riềng",
        "Gò Quao",
        "Hà Tiên",
        "Rạch Giá",
    ],
    "Kon Tum" => [
        "Ia H'Drai",
        "Kon Plông",
        "Kon Rẫy",
        "Kon Tum",
        "Tu Mơ Rông",
        "Ngọc Hồi",
        "Đắk Glei",
        "Đắk Hà",
        "Đăk Tô",
        "Sa Thầy",
    ],
    "Lai Châu" => [
        "Sìn Hồ",
        "Tam Đường",
        "Tân Uyên",
        "Than Uyên",
        "Lai Châu",
        "Mường Tè",
        "Nậm Nhùn",
        "Phong Thổ",
    ],
    "Lâm Đồng" => [
        "Bảo Lâm",
        "Bảo Lộc",
        "Lạc Dương",
        "Lâm Hà",
        "Cát Tiên",
        "Di Linh",
        "Đà Lạt",
        "Đạ Huoai",
        "Đạ Tẻh",
        "Đam Rông",
        "Đơn Dương",
        "Đức Trọng",
    ],
    "Lạng Sơn" => [
        "Hữu Lũng",
        "Bắc Sơn",
        "Bình Gia",
        "Lạng Sơn",
        "Cao Lộc",
        "Lộc Bình",
        "Tràng Định",
        "Chi Lăng",
        "Văn Lãng",
        "Văn Quan",
        "Đình Lập",
    ],
    "Lào Cai" => [
        "Si Ma Cai",
        "Bảo Thắng",
        "Bảo Yên",
        "Bát Xát",
        "Bắc Hà",
        "Lào Cai",
        "Mường Khương",
        "Văn Bàn",
        "Sa Pa",
    ],
    "Long An" => [
        "Tân An",
        "Tân Hưng",
        "Kiến Tường",
        "Tân Thạnh",
        "Tân Trụ",
        "Bến Lức",
        "Thạnh Hóa",
        "Thủ Thừa",
        "Cần Đước",
        "Cần Giuộc",
        "Châu Thành",
        "Mộc Hóa",
        "Vĩnh Hưng",
        "Đức Hòa",
        "Đức Huệ",
    ],
    "Nam Định" => [
        "Trực Ninh",
        "Mỹ Lộc",
        "Nam Định",
        "Nam Trực",
        "Nghĩa Hưng",
        "Vụ Bản",
        "Xuân Trường",
        "Ý Yên",
        "Giao Thủy",
        "Hải Hậu",
    ],
    "Nghệ An" => [
        "Hoàng Mai",
        "Anh Sơn",
        "Hưng Nguyên",
        "Tân Kỳ",
        "Thái Hòa",
        "Kỳ Sơn",
        "Thanh Chương",
        "Con Cuông",
        "Nam Đàn",
        "Tương Dương",
        "Cửa Lò",
        "Diễn Châu",
        "Nghi Lộc",
        "Nghĩa Đàn",
        "Vinh",
        "Đô Lương",
        "Yên Thành",
        "Quế Phong",
        "Quỳ Châu",
        "Quỳ Hợp",
        "Quỳnh Lưu",
    ],
    "Ninh Bình" => [
        "Tam Điệp",
        "Kim Sơn",
        "Nho Quan",
        "Ninh Bình",
        "Yên Khánh",
        "Yên Mô",
        "Gia Viễn",
        "Hoa Lư",
    ],
    "Ninh Thuận" => [
        "Bác Ái",
        "Thuận Bắc",
        "Thuận Nam",
        "Ninh Hải",
        "Ninh Phước",
        "Ninh Sơn",
        "Phan Rang-Tháp Chàm",
    ],
    "Phú Thọ" => [
        "Tam Nông",
        "Tân Sơn",
        "Thanh Ba",
        "Thanh Sơn",
        "Thanh Thủy",
        "Lâm Thao",
        "Cẩm Khê",
        "Việt Trì",
        "Đoan Hùng",
        "Yên Lập",
        "Phú Thọ",
        "Phù Ninh",
        "Hạ Hòa",
    ],
    "Phú Yên" => [
        "Sông Cầu",
        "Sông Hinh",
        "Sơn Hòa",
        "Tây Hòa",
        "Tuy An",
        "Tuy Hòa",
        "Phú Hòa",
        "Đông Hòa",
        "Đồng Xuân",
    ],
    "Quảng Bình" => [
        "Ba Đồn",
        "Bố Trạch",
        "Lệ Thủy",
        "Minh Hóa",
        "Tuyên Hóa",
        "Đồng Hới",
        "Quảng Ninh",
        "Quảng Trạch",
    ],
    "Quảng Nam" => [
        "Hội An",
        "Tam Kỳ",
        "Bắc Trà My",
        "Tây Giang",
        "Thăng Bình",
        "Tiên Phước",
        "Nam Giang",
        "Nam Trà My",
        "Duy Xuyên",
        "Đại Lộc",
        "Điện Bàn",
        "Nông Sơn",
        "Núi Thành",
        "Đông Giang",
        "Phú Ninh",
        "Phước Sơn",
        "Quế Sơn",
        "Hiệp Đức",
    ],
    "Quảng Ngãi" => [
        "Sơn Hà",
        "Sơn Tây",
        "Ba Tơ",
        "Sơn Tịnh",
        "Tây Trà",
        "Bình Sơn",
        "Lý Sơn",
        "Trà Bồng",
        "Minh Long",
        "Mộ Đức",
        "Tư Nghĩa",
        "Nghĩa Hành",
        "Đức Phổ",
        "Quảng Ngãi",
    ],
    "Quảng Ninh" => [
        "Hoành Bồ",
        "Ba Chẽ",
        "Bình Liêu",
        "Cẩm Phả",
        "Tiên Yên",
        "Móng Cái",
        "Cô Tô",
        "Uông Bí",
        "Vân Đồn",
        "Đầm Hà",
        "Đông Triều",
        "Quảng Yên",
        "Hạ Long",
        "Hải Hà",
    ],
    "Quảng Trị" => [
        "Hướng Hóa",
        "Cam Lộ",
        "Triệu Phong",
        "Cồn Cỏ",
        "Đa Krông",
        "Vĩnh Linh",
        "Đông Hà",
        "Gio Linh",
        "Quảng Trị",
        "Hải Lăng",
    ],
    "Sóc Trăng" => [
        "Sóc Trăng",
        "Kế Sách",
        "Thạnh Trị",
        "Long Phú",
        "Châu Thành",
        "Trần Đề",
        "Mỹ Tú",
        "Mỹ Xuyên",
        "Cù Lao Dung",
        "Ngã Năm",
        "Vĩnh Châu",
    ],
    "Sơn La" => [
        "Sông Mã",
        "Sốp Cộp",
        "Sơn La",
        "Bắc Yên",
        "Thuận Châu",
        "Mai Sơn",
        "Mộc Châu",
        "Mường La",
        "Vân Hồ",
        "Yên Châu",
        "Phù Yên",
        "Quỳnh Nhai",
    ],
    "Tây Ninh" => [
        "Tân Biên",
        "Tân Châu",
        "Bến Cầu",
        "Tây Ninh",
        "Châu Thành",
        "Trảng Bàng",
        "Dương Minh Châu",
        "Gò Dầu",
        "Hòa Thành",
    ],
    "Thái Bình" => [
        "Hưng Hà",
        "Kiến Xương",
        "Thái Bình",
        "Thái Thụy",
        "Tiền Hải",
        "Vũ Thư",
        "Đông Hưng",
        "Quỳnh Phụ",
    ],
    "Thái Nguyên" => [
        "Sông Công",
        "Thái Nguyên",
        "Đại Từ",
        "Võ Nhai",
        "Định Hóa",
        "Phổ Yên",
        "Phú Bình",
        "Phú Lương",
        "Đồng Hỷ",
    ],
    "Thanh Hóa" => [
        "Hoằng Hóa",
        "Bá Thước",
        "Bỉm Sơn",
        "Thạch Thành",
        "Thanh Hóa",
        "Lang Chánh",
        "Thiệu Hóa",
        "Thọ Xuân",
        "Cẩm Thủy",
        "Thường Xuân",
        "Tĩnh Gia",
        "Mường Lát",
        "Triệu Sơn",
        "Nga Sơn",
        "Ngọc Lặc",
        "Như Thanh",
        "Như Xuân",
        "Vĩnh Lộc",
        "Nông Cống",
        "Yên Định",
        "Đông Sơn",
        "Quan Hóa",
        "Quan Sơn",
        "Quảng Xương",
        "Hà Trung",
        "Hậu Lộc",
        "Sầm Sơn",
    ],
    "Tiền Giang" => [
        "Tân Phú Đông",
        "Tân Phước",
        "Cai Lậy",
        "Cai Lậy",
        "Cái Bè",
        "Châu Thành",
        "Chợ Gạo",
        "Mỹ Tho",
        "Gò Công",
        "Gò Công Đông",
        "Gò Công Tây",
    ],
    "Trà Vinh" => [
        "Càng Long",
        "Cầu Kè",
        "Cầu Ngang",
        "Tiểu Cần",
        "Trà Cú",
        "Trà Vinh",
        "Châu Thành",
        "Duyên Hải",
        "Duyên Hải",
    ],
    "Tuyên Quang" => [
        "Sơn Dương",
        "Lâm Bình",
        "Chiêm Hóa",
        "Na Hang",
        "Tuyên Quang",
        "Yên Sơn",
        "Hàm Yên",
    ],
    "Vĩnh Long" => [
        "Tam Bình",
        "Bình Minh",
        "Bình Tân",
        "Long Hồ",
        "Mang Thít",
        "Trà Ôn",
        "Vĩnh Long",
        "Vũng Liêm",
    ],
    "Vĩnh Phúc" => [
        "Sông Lô",
        "Tam Dương",
        "Tam Đảo",
        "Bình Xuyên",
        "Lập Thạch",
        "Vĩnh Tường",
        "Vĩnh Yên",
        "Yên Lạc",
        "Phúc Yên",
    ],
    "Yên Bái" => [
        "Lục Yên",
        "Trạm Tấu",
        "Mù Căng Chải",
        "Trấn Yên",
        "Văn Chấn",
        "Văn Yên",
        "Nghĩa Lộ",
        "Yên Bái",
        "Yên Bình",
    ],
];
function getProvince()
{
    return $province;
}